image: 'python:3.7.4-buster'

before_script:
  - mkdir -p /tmp/get-poetry/
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry/get-poetry.py
  - python /tmp/get-poetry/get-poetry.py --version 1.0.2
  - source "$HOME/.poetry/env"
  - poetry -V
  # install dependencies to current python interpreter
  - poetry config virtualenvs.create false
  - poetry install
  - poetry show

tests:
  script:
    - pytest
