image: 'registry.gitlab.com/artslob/cyberbox/ci-image:latest'

before_script:
  - source /ci-image/venv/bin/activate
  - pip list
  - poetry -V
  - poetry install
  - poetry show

tests:
  services:
    - name: postgres:12.2
      alias: db
  variables:
    POSTGRES_PASSWORD: testpass
    POSTGRES_USER: testuser
    POSTGRES_DB: cyberbox-test
    CYBERBOX_TEST_DB_URL: "postgresql://testuser:testpass@db:5432/cyberbox-test"
  script:
    - pytest --color=yes

black:
  script:
    - black --check .

isort:
  script:
    - isort -rc --check-only .

flake8:
  script:
    - flake8 .
