image: 'registry.gitlab.com/artslob/cyberbox/ci-image:latest'

before_script:
  - pip list
  - poetry -V
  - poetry install
  - poetry show

tests:
  services:
    - name: postgres:10.12
      alias: db
  variables:
    POSTGRES_PASSWORD: testpass
    POSTGRES_USER: testuser
    POSTGRES_DB: cyberbox-test
    CYBERBOX_TEST_DB_URL: "postgresql://testuser:testpass@db:5432/cyberbox-test"
  script:
    - coverage run -m pytest --color=yes
    - coverage report

upgrade-downgrade-db:
  services:
    - name: postgres:10.12
      alias: db
  variables:
    POSTGRES_PASSWORD: testpass
    POSTGRES_USER: testuser
    POSTGRES_DB: cyberbox-test
    CYBERBOX_TEST_DB_URL: "postgresql://testuser:testpass@db:5432/cyberbox-test"
  script:
    - python .ci/upgrade_and_downgrade_db.py

compare-migrations-metadata:
  services:
    - name: postgres:10.12
      alias: db
  variables:
    POSTGRES_PASSWORD: testpass
    POSTGRES_USER: testuser
    POSTGRES_DB: cyberbox-test
    CYBERBOX_TEST_DB_URL: "postgresql://testuser:testpass@db:5432/cyberbox-test"
  script:
    - psql --version
    - ./.ci/make_dump.sh meta > meta
    - ./.ci/make_dump.sh migration > migration
    - diff --color=always migration meta

code-style:
  script:
    - black --check .
    - isort -rc --check-only .
    - flake8 .
