version: '3.7'

services:

  cyberbox:
    build: .
    ports:
      - 9000:8000
    environment:
      CYBERBOX_CONFIG_FILE: "/cyberbox/configs/config-docker.yaml"
    volumes:
      - .:/cyberbox
    depends_on:
      - db
    restart: always

  db:
    image: 'postgres:10.12'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_USER: devuser
      POSTGRES_DB: cyberbox-db
    restart: always

  test-db:
    image: 'postgres:10.12'
    ports:
      - '6432:5432'
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: testuser
      POSTGRES_DB: cyberbox-test
    restart: always
